name: Test Hugging Face Model
on: workflow_dispatch

jobs:
  test_model:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install requests
      - name: Test HF Model
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: python scripts/test_model.py
