name: Generar curiosidades
on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * *'  # diario a las 07:00 UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install requirements
        run: pip install --upgrade pip && pip install requests
      - name: Run generator
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_MODEL: mistralai/Mistral-7B-Instruct-v0.3
        run: python scripts/generate_post.py
      - name: Commit & push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions[bot]"
          git add _posts curiosidades.json
          git commit -m "Auto: generar curiosidades" || echo "No hay cambios"
          git push
