name: Generar curiosidades automáticamente

on:
  workflow_dispatch:   # permite ejecución manual desde GitHub
  schedule:
    - cron: '0 7 * * *'  # todos los días a las 07:00 UTC

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Descargar el repo
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2️⃣ Configurar Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 3️⃣ Instalar librerías necesarias
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # 4️⃣ Ejecutar script de generación
      - name: Generar datos curiosos
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}         # tu token guardado en GitHub Secrets
          HF_MODEL: HuggingFaceH4/zephyr-7b-beta    # ✅ modelo compatible
        run: python scripts/generate_post.py

      # 5️⃣ Guardar cambios en el repo
      - name: Commit y push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions[bot]"
          git add _posts curiosidades.json
          git commit -m "Auto: generar 5 nuevos datos curiosos" || echo "No hay cambios para commitear"
          git push
