name: Generar Curiosidades

on:
  schedule:
    - cron: '0 10 * * *'  # Corre todos los días a las 10:00 AM
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: python scripts/generate_post_dual_optimized.py
