name: Auto-generate 5 curiosity posts

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Corre todos los días a medianoche UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install requirements
      run: pip install requests

    - name: Run generate_post script
      run: python scripts/generate_post.py

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add _posts/ public/curiosidades.json curiosidades.json
        git commit -m "Auto-generate 5 curiosity posts" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
