name: Generar curiosidades seguras con dos modelos

on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * *'

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install requests
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Generar datos curiosos
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: python scripts/generate_post_dual_safe.py

      - name: Commit y push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions[bot]"
          git add _posts curiosidades.json
          git commit -m "Auto: generar 5 nuevos datos curiosos" || echo "No hay cambios"
          git push

