name: Generar Curiosidades

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Opcional: ejecuta diariamente a medianoche

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - run: pip install requests

      - name: Generar datos curiosos
        run: python scripts/generate_post_dual_optimized.py
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}

      - name: Configurar Git
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit y push automáticos
        run: |
          git add curiosidades.json
          git commit -m "Auto: generar nuevas curiosidades" || echo "Sin cambios que commitear"
          git push
