name: Test Hugging Face Model
on: workflow_dispatch

jobs:
  test_model:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install requests
      - name: Test HF Model
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python - << 'EOF'
          import requests
          import os
          HF_TOKEN = os.getenv("HF_TOKEN")
          MODEL = "TinyLlama/TinyLlama-1.1B-intermediate-step-1431k-3T"

          response = requests.post(
              f"https://api-inference.huggingface.co/models/{MODEL}",
              headers={"Authorization": f"Bearer {HF_TOKEN}"},
              json={"inputs": "Hola, genera un ejemplo de dato curioso."}
          )
          print("Status code:", response.status_code)
          print("Response:", response.text)
          EOF
